import datetime
from haystack import indexes
from .models import Monitorable


class NoteIndex(indexes.SearchIndex, indexes.Indexable):
	#title = models.TextField(blank=True, null=True, db_index=True)
	description = models.TextField()ue)
	cup= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	#original_data = models.TextField(blank=True, null=True, db_index=True)

	COD_LOCALE_PROGETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)

	DPS_FINANZ_TOT_PUB_NETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCRIZIONE_ATECO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCRIZIONE_GRANDE_PROGETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_DESCR_OBIETTIVO_GENERALE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_COD_TIPOLOGIA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	LINK= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_COD_NATURA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_LINEA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DATA_FINE_EFFETTIVA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_COD_TEMA_PRIORITARIO_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_COD_OBIETTIVO_GENERALE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_DESCR_TIPOLOGIA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	ECONOMIE_TOTALI= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_STRUMENTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_PRIVATO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_COD_FONTE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	PO_CODICE_ASSE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	PO_COD_OBIETTIVO_OPERATIVO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_FLAG_PAC= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_STRUMENTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_DA_REPERIRE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_COD_PRIORITA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_COD_SOTTOSETTORE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_COD_CATEGORIA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_EFFETTIVA_FINE_PROC_ATTIV= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	PO_DENOMINAZIONE_ASSE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_PROVINCIA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_LINEA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_FONDO_COMUNITARIO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_TIPO_PROGETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_COD_TEMA_SINTETICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	TOT_PAGAMENTI_RENDICONTABILI_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_DESCR_CATEGORIA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_AZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_STATO_ALTRI_PROVVEDIMENTI= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_TIPO_PROCED_ATTIVAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DATA_INIZIO_PREVISTA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_PROCED_ATTIVAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COSTO_RENDICONTABILE_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_STATO_FSC= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_COMUNE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	ECONOMIE_TOTALI_PUBBLICHE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_STATO_FONDO_DI_ROTAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_COD_SETTORE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	IMPEGNI= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_DESCR_SOTTOSETTORE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_ADOZIONE_DELIBERA_CIPE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_DESCR_SETTORE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_FLAG_COERENZA_DATE_PREV= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_DESCRIZIONE_PRIORITA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DELIBERA_CIPE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DATA_INIZIO_EFFETTIVA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_PUBBLICAZIONE_DELIBERA_CIPE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_GRANDE_PROGETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DESCRIZIONE_PROGRAMMA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	TOT_PAGAMENTI= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_TOTALE_PUBBLICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_ATECO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_DESCR_TEMA_PRIORITARIO_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_RISORSE_LIBERATE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_FLAG_CUP= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DATA_FINE_PREVISTA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_REGIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_CODICE_OBIETTIVO_SPECIFICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	CUP_DESCR_NATURA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_TIPO_STRUMENTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_FLAG_COERENZA_DATE_EFF= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_TITOLO_PROGETTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_TIPO_PROCED_ATTIVAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_ALTRO_PUBBLICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_APPROV_STRUMENTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_PREVISTA_FINE_PROC_ATTIV= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	TOT_PAGAMENTI_FSC= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_EFFETTIVA_BANDO_PROC_ATTIV= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_DESCR_OBIETTIVO_SPECIFICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	QSN_AREA_OBIETTIVO_UE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DESCR_AZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_AGGIORNAMENTO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_STATO_PAC= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	COD_PROCED_ATTIVAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	PO_OBIETTIVO_OPERATIVO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_FLAG_PRESENZA_DATE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_DESCR_FONTE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	NOTE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DATA_PREVISTA_BANDO_PROC_ATTIV= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_TEMA_SINTETICO= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_TIPO_PROGRAMMAZIONE= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	DPS_CODICE_PROGRAMMA= models.CharField(max_length=500, null=True, blank=True, db_index=True)
	FINANZ_STATO_ESTERO= models.CharField(max_length=500, null=True, blank=True, db_index=True)

    def get_model(self):
        return Monitorable

    def index_queryset(self, using=None):
        """Used when the entire index for model is updated."""
        return self.get_model().objects.filter(pub_date__lte=datetime.datetime.now())