# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20150208_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorable',
            name='COD_ATECO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_AZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_GRANDE_PROGETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_LINEA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_LOCALE_PROGETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_PROCED_ATTIVAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_STRUMENTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COD_TIPO_PROCED_ATTIVAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='COSTO_RENDICONTABILE_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_COD_CATEGORIA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_COD_NATURA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_COD_SETTORE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_COD_SOTTOSETTORE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_COD_TIPOLOGIA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_DESCR_CATEGORIA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_DESCR_NATURA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_DESCR_SETTORE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_DESCR_SOTTOSETTORE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='CUP_DESCR_TIPOLOGIA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_ADOZIONE_DELIBERA_CIPE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_AGGIORNAMENTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_APPROV_STRUMENTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_EFFETTIVA_BANDO_PROC_ATTIV',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_EFFETTIVA_FINE_PROC_ATTIV',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_PREVISTA_BANDO_PROC_ATTIV',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_PREVISTA_FINE_PROC_ATTIV',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DATA_PUBBLICAZIONE_DELIBERA_CIPE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCRIZIONE_ATECO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCRIZIONE_GRANDE_PROGETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_AZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_LINEA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_PROCED_ATTIVAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_STRUMENTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_TIPO_PROCED_ATTIVAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DESCR_TIPO_STRUMENTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_CODICE_PROGRAMMA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_COD_FONTE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_COD_TEMA_SINTETICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DATA_FINE_EFFETTIVA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DATA_FINE_PREVISTA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DATA_INIZIO_EFFETTIVA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DATA_INIZIO_PREVISTA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DELIBERA_CIPE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DESCRIZIONE_PROGRAMMA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_DESCR_FONTE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FINANZ_TOT_PUB_NETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FLAG_COERENZA_DATE_EFF',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FLAG_COERENZA_DATE_PREV',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FLAG_CUP',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FLAG_PAC',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_FLAG_PRESENZA_DATE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_TEMA_SINTETICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_TIPO_PROGETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_TIPO_PROGRAMMAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='DPS_TITOLO_PROGETTO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='ECONOMIE_TOTALI',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='ECONOMIE_TOTALI_PUBBLICHE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_ALTRO_PUBBLICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_COMUNE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_DA_REPERIRE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_PRIVATO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_PROVINCIA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_REGIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_RISORSE_LIBERATE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_STATO_ALTRI_PROVVEDIMENTI',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_STATO_ESTERO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_STATO_FONDO_DI_ROTAZIONE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_STATO_FSC',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_STATO_PAC',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_TOTALE_PUBBLICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='FINANZ_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='IMPEGNI',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='LINK',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='NOTE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='PO_CODICE_ASSE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='PO_COD_OBIETTIVO_OPERATIVO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='PO_DENOMINAZIONE_ASSE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='PO_OBIETTIVO_OPERATIVO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_AREA_OBIETTIVO_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_CODICE_OBIETTIVO_SPECIFICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_COD_OBIETTIVO_GENERALE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_COD_PRIORITA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_COD_TEMA_PRIORITARIO_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_DESCRIZIONE_PRIORITA',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_DESCR_OBIETTIVO_GENERALE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_DESCR_OBIETTIVO_SPECIFICO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_DESCR_TEMA_PRIORITARIO_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='QSN_FONDO_COMUNITARIO',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='TOT_PAGAMENTI',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='TOT_PAGAMENTI_FSC',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='TOT_PAGAMENTI_RENDICONTABILI_UE',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='cup',
            field=models.CharField(db_index=True, max_length=500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='date_from',
            field=models.DateField(db_index=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='date_to',
            field=models.DateField(db_index=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='locations',
            field=models.ManyToManyField(db_index=True, to='projects.Location', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='oc_slug',
            field=models.CharField(db_index=True, max_length=100, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='oc_url',
            field=models.URLField(db_index=True, max_length=400, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='paid_amount',
            field=models.FloatField(db_index=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='paid_percent',
            field=models.FloatField(db_index=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='subjects',
            field=models.ManyToManyField(db_index=True, to='projects.Subject', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='projects.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='monitorable',
            name='total_amount',
            field=models.FloatField(db_index=True, null=True, blank=True),
            preserve_default=True,
        ),
    ]
